### ISSUE TITLE
If you open the inventory, the Elder Guardian's position is too low 

### ISSUE THREAD

**Issue by alfare** [cda94581/Community_Collabs#100]
![Screenshot_20210817_094148_5c8300b655012b1930f2e0a7b81bf6a9~2](https://user-images.githubusercontent.com/83904810/129667158-08a4a8cb-5526-4329-a621-fd6720f3b173.jpg)
The position is too low, thus closing the player inventory slot

**Comment by cda94581** [comment]
Possibly look into combining with #96, renaming to something like "Inventory Preview Issues"?

**Comment by cda94581** [comment]
Hey there! This project has been moved to a [new repository](https://github.com/cda94581/cdas-morph), and as such this issue will be closed. Feel free to reopen any bugs in the new location
