### ISSUE TITLE
Ghast visual size too small

### ISSUE THREAD

**Issue by cda94581** [cda94581/Community_Collabs#18]
When morphing, the Ghast visual size is too small for their collision box of 4x4.

Fixed in 0.0.4

**Comment by Hidden-Trial** [comment]
Hello,

Copy and apply this into your Ghast "component groups" in your player.json file in your entities folder:  		

"minecraft:scale": {
          "value": 3.5
        }

Although admittedly, you can apply this string to most of your component groups to make more sub-mobs. For example, you can decrease the zombie model's size to 0.5 to make a 'new' baby variant. The possibilities are endless and really easy to accomplish. Giant zombie variant, maybe?
