### ISSUE TITLE
Sometimes will not burn in daylight/lava for entities that should burn, because others have "minecraft:fire_immune" component, relogging fixes this

### ISSUE THREAD

**Issue by cda94581** [cda94581/Community_Collabs#5]
Sometimes the mobs that should burn in daylight or in lava don't burn. This is because some mobs have the "minecraft:fire_immune" component. Relogging appears to fix this.
The mobs affected are:
- Player
- Creeper
- Drowned
- Elder Guardian
- Endermite
- Evoker
- Guardian
- Hoglin
- Husk
- Phantom
- Piglin Brute
- Pillager
- Ravager
- Shulker
- Silverfish
- Skeleton
- Slime
- Stray
- Vindicator
- Witch
- Zombie
- Zombie Villager

The mobs that are immune are:
- Blaze
- Ghast
- Magma Cube
- Vex
- Wither Skeleton
- Zoglin

Steps to reproduce:
1. Morph into an unimmune mob
2. `/gamemode s`
3. Step into lava
4. You should burn
5. Morph into an immune mob and step into lava
6. You shouldn't burn
7. Morph back into an unimmune mob and step into lava

Expected result: You burn after Step 7
Actual result: You don't burn after Step 7

Suggested fixes:
- [`/effect fire_resistance`](https://discord.com/channels/523663022053392405/525070015762792459/826928964199120919)

Fixed in 0.0.4

**Comment by Hidden-Trial** [comment]
The "minecraft:fire_immune" is not the component you are looking for. Regarding if you want your mobs to burn. Copy and paste/make sure you have "minecraft:burns_in_daylight": {}, in every component group. Hope this helps.

**Comment by cda94581** [comment]
The problem with `minecraft:burns_in_daylight` would be that they would also burn in the sunlight, which would cause even more issues 😅
