### ISSUE TITLE
Camera won't adjust based on entity size

### ISSUE THREAD

**Issue by cda94581** [cda94581/Community_Collabs#6]
Based on the size and height of an entity, the camera should adjust so that it feels like you are that mob.
Steps to reproduce:
1. Enter 1st Person
2. Morph into a Player and then observe - This is a tall entity so the camera should be higher above the ground
3. Morph into an Endermite and then observe - This is a short entity so the camera should be closer to the ground

Expected result: Camera adjusts to be closer to the ground and things look bigger
Actual result: Camera stays the same height above the ground things don't change in size

As far as I am aware, and like **Hidden-Trial** said, unfortunately add-ons are not currently capable of doing this. Experimentation is welcome, but this is likely to be a bug that would be fixed in the far future, or never.

**Comment by Hidden-Trial** [comment]
I don't believe we have the necessary code that would allow us to modify the camera to the best of my knowledge. We only have the tools to modify the first-person animations but not the actual camera angle.

**Comment by cda94581** [comment]
It appears there may be a move to make cameras data-driven. This is reflected through [this link](https://discord.com/channels/494194063730278411/914293760085614594) on the Bedrock OSS Discord server.

I will be paying attention to this to see if it's possible some time in the near-ish future

**Comment by cda94581** [comment]
Project moved to [new repository](https://github.com/cda94581/cdas-morph)
