### ISSUE TITLE
Allow Spider to climb up walls

### ISSUE THREAD

**Issue by GitHubBoiii** [cda94581/Community_Collabs#89]
i cant climb walls like a spider does

https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.minecraftmods.com%2Fwp-content%2Fuploads%2F2015%2F09%2Fspider.png&imgrefurl=https%3A%2F%2Fwww.minecraftmods.com%2Fmorph-mod%2F&tbnid=6gEMcq3bK8FhaM&vet=12ahUKEwjYp-79xLbyAhWCYDUKHU9GB7IQMygOegUIARDQAQ..i&docid=a_TUV_c67q6nNM&w=1920&h=1080&q=spider%20climbing%20walls%20in%20minecraft&ved=2ahUKEwjYp-79xLbyAhWCYDUKHU9GB7IQMygOegUIARDQAQ

**Comment by cda94581** [comment]
Hey there! This project has been moved to a [new repository](https://github.com/cda94581/cdas-morph), and as such this issue will be closed. Feel free to reopen any bugs in the new location
