### ISSUE TITLE
Magma Cube/Slime can only be baby size

### ISSUE THREAD

**Issue by cda94581** [cda94581/Community_Collabs#9]
Magma Cubes and Slime are only baby sized and cannot be changed

**Comment by Hidden-Trial** [comment]
Yea, it seems like most of your size issue has got to do with the missing scale component. 	

"minecraft:scale": {
          "value": x
        }

**Comment by cda94581** [comment]
Project moved to [new repository](https://github.com/cda94581/cdas-morph)
