### ISSUE TITLE
Armor renders improperly

### ISSUE THREAD

**Issue by alfare** [cda94581/Community_Collabs#90]
![Screenshot_20210817_092724_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/83904810/129654488-0de9d199-732a-4b4b-bbb7-e25d332f9ec7.jpg)
Me 
![Screenshot_20210817_092718_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/83904810/129654492-94b118e6-5862-4ff0-ad94-94efc570d429.jpg)
I have I have a suggestion to fix the bug, what if the player turns into morph armor and the item is not visible if held and worn when the player turns into a morph. In camera Third person back and third person front, so the bugs when wearing armor and holding items will be resolved. How is that a good idea isn't it?

**Comment by cda94581** [comment]
The items portion is addressed in #7. Would you like to consider moving the rest of this bug report to #7 as well?

**Comment by alfare** [comment]
> Bagian item dibahas di #7 . Apakah Anda ingin mempertimbangkan untuk memindahkan sisa laporan bug ini ke #7 juga?

the method? do i have to make a new bug report?

**Comment by cda94581** [comment]
No need, just comment on #7.

**Comment by cda94581** [comment]
Hey there! This project has been moved to a [new repository](https://github.com/cda94581/cdas-morph), and as such this issue will be closed. Feel free to reopen any bugs in the new location
