### ISSUE TITLE
Wolf tail renders improperly

### ISSUE THREAD

**Issue by alfare** [cda94581/Community_Collabs#93]
![Screenshot_20210817_100202_5c8300b655012b1930f2e0a7b81bf6a9~2](https://user-images.githubusercontent.com/83904810/129666488-99ed0f89-4c46-431f-9c9d-85f28e5a42f5.jpg)
Looks like this is a texture bug on wolves

**Comment by cda94581** [comment]
Hey there! This project has been moved to a [new repository](https://github.com/cda94581/cdas-morph), and as such this issue will be closed. Feel free to reopen any bugs in the new location
