### ISSUE TITLE
Weird squat animation on fox and zombie husk

### ISSUE THREAD

**Issue by alfare** [cda94581/Community_Collabs#94]
![Screenshot_20210817_100219_5c8300b655012b1930f2e0a7b81bf6a9~2](https://user-images.githubusercontent.com/83904810/129666644-ad4e0b4c-8ce1-4df1-b8d8-33b2ea3f4fcb.jpg)
![Screenshot_20210817_095827_5c8300b655012b1930f2e0a7b81bf6a9~2](https://user-images.githubusercontent.com/83904810/129666666-80d07152-66e2-4488-8a7d-0151b9bd1266.jpg)

**Comment by cda94581** [comment]
Duplicated by #11.
