### ISSUE TITLE
If you open the inventory, the ghast has no texture on its face

### ISSUE THREAD

**Issue by alfare** [cda94581/Community_Collabs#96]
![Screenshot_20210817_095458_5c8300b655012b1930f2e0a7b81bf6a9~2](https://user-images.githubusercontent.com/83904810/129666880-98be5079-bf72-43b1-8ed6-b16dd2a988d7.jpg)

**Comment by cda94581** [comment]
Hey there! This project has been moved to a [new repository](https://github.com/cda94581/cdas-morph), and as such this issue will be closed. Feel free to reopen any bugs in the new location
