### ISSUE TITLE
Weird walking animation on turtles

### ISSUE THREAD

**Issue by alfare** [cda94581/Community_Collabs#97]
![Screenshot_20210817_095443_5c8300b655012b1930f2e0a7b81bf6a9~2](https://user-images.githubusercontent.com/83904810/129666967-0c84e749-8685-4751-9fa7-3477d637202d.jpg)

**Comment by cda94581** [comment]
Might want to look into renaming #4 to also include these weird animations, leaving this open for now though.

**Comment by alfare** [comment]
> Mungkin ingin melihat penggantian nama #4 untuk juga menyertakan animasi aneh ini, biarkan ini terbuka untuk saat ini.

ok, I'll leave it open for now

**Comment by cda94581** [comment]
Hey there! This project has been moved to a [new repository](https://github.com/cda94581/cdas-morph), and as such this issue will be closed. Feel free to reopen any bugs in the new location
