### ISSUE TITLE
Rabbits don't have ear texture, on their heads

### ISSUE THREAD

**Issue by alfare** [cda94581/Community_Collabs#98]
![Screenshot_20210817_095417_5c8300b655012b1930f2e0a7b81bf6a9~2](https://user-images.githubusercontent.com/83904810/129667014-893f4330-2da9-4e75-94be-79679a3a5488.jpg)

**Comment by cda94581** [comment]
Hey there! This project has been moved to a [new repository](https://github.com/cda94581/cdas-morph), and as such this issue will be closed. Feel free to reopen any bugs in the new location
