### ISSUE TITLE
Glow squid has no animation, like in vanilla Minecraft

### ISSUE THREAD

**Issue by alfare** [cda94581/Community_Collabs#99]
![Screenshot_20210817_094614_5c8300b655012b1930f2e0a7b81bf6a9~2](https://user-images.githubusercontent.com/83904810/129667086-37e47787-666b-433e-b346-1e4649d972a7.jpg)

**Comment by cda94581** [comment]
I believe this also applies to Squid as well. I will reopen #4 and mark this as a duplicate of that. If you want to contribute to that issue, feel free.
